version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskqueue
    ports:
      # Maps port 5432 inside the container to 5432 on your laptop
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: